project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!deprecated/"

execute:
  freeze: auto

website:
  title: "Examined Algorithms"
  description: The personal website of Nathaniel Forde
  reader-mode: true
  navbar:
    left:
      - text: Blog
        href: blog.qmd
      - text: Open Source Projects
        href: opensource.qmd
      - text: Talks
        href: talks.qmd
      - text: CV
        href: /resume/Nathaniel_Forde_CV.pdf
      - icon: github
        href: https://github.com/NathanielF
      - icon: twitter
        href: https://twitter.com/forde_nathaniel


  
  sidebar:
    title: Notes
    pinned: false
    collapse-level: 1
    style: docked
    contents: notes/certain_things/Public/**

format:
  html:
    theme: [flatly]
    css:
      - styles.css
    toc: true


exclude:
  - "posts/deprecated/"

