name: pytorch-env
channels:
  - conda-forge
dependencies:
  - python=3.10   # or 3.11
  - pytorch
  - jupyterlab
  - matplotlib
  - numpy
  - pip                 # allows pip installs
  - pip:
      - "bayesflow>=2.0"

